/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */

export interface AccountInfoCreateRequest {
  /** @nullable */
  field?: string | null;
  /** @nullable */
  value?: string | null;
}
