/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */

export interface ArticleDto {
  id?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  isPrivate?: boolean;
  accountId?: string;
  /** @nullable */
  typeArticleId?: string | null;
}
