/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { Article } from "./article";

export interface ArticleIEnumerableApiResponse {
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: Article[] | null;
}
