/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { ArticleBranchDto } from "./articleBranchDto";

export interface ArticleBranchDtoApiResponse {
  /** @nullable */
  message?: string | null;
  data?: ArticleBranchDto;
}
