/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { Account } from "./account";
import type { Article } from "./article";
import type { ArticlePermissionLevel } from "./articlePermissionLevel";
import type { ArticleBranch } from "./articleBranch";
import type { ArticleBranchVersion } from "./articleBranchVersion";

export interface ArticleParticipant {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  accountId?: string;
  account?: Account;
  isAccepted?: boolean;
  articleId?: string;
  article?: Article;
  permissionLevel?: ArticlePermissionLevel;
  /** @nullable */
  articleBranches?: ArticleBranch[] | null;
  /** @nullable */
  articleBranchVersions?: ArticleBranchVersion[] | null;
}
