/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { Article } from "./article";
import type { ArticleParticipant } from "./articleParticipant";
import type { ArticleBranchVersion } from "./articleBranchVersion";

export interface ArticleBranch {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  name?: string | null;
  articleId?: string;
  article?: Article;
  creatorId?: string;
  creator?: ArticleParticipant;
  /** @nullable */
  articleBranchVersions?: ArticleBranchVersion[] | null;
}
