/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */

export type ArticlePermissionLevel =
  (typeof ArticlePermissionLevel)[keyof typeof ArticlePermissionLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArticlePermissionLevel = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
