/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { ArticleParticipant } from "./articleParticipant";
import type { ArticleBranch } from "./articleBranch";

export interface ArticleBranchVersion {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  text?: string | null;
  articleParticipantId?: string;
  articleParticipant?: ArticleParticipant;
  articleBranchId?: string;
  articleBranch?: ArticleBranch;
}
