/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */

export interface ArticleType {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  name?: string | null;
}
