/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { Account } from "./account";
import type { ArticleParticipant } from "./articleParticipant";
import type { ArticleBranch } from "./articleBranch";
import type { ArticleType } from "./articleType";

export interface Article {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  isPrivate?: boolean;
  accountId?: string;
  account?: Account;
  /** @nullable */
  articleParticipants?: ArticleParticipant[] | null;
  /** @nullable */
  articleBranches?: ArticleBranch[] | null;
  /** @nullable */
  typeArticleId?: string | null;
  articleType?: ArticleType;
}
