/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */

export interface CreateBranchDto {
  /** @nullable */
  parentId?: string | null;
  /** @nullable */
  name?: string | null;
}
