/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { NotificationType } from "./notificationType";

export interface Notification {
  id?: number;
  account_id?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  message?: string | null;
  type?: NotificationType;
  is_read?: boolean;
  readed_date?: string;
  created_at?: string;
}
