/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { ArticlePermissionLevel } from "./articlePermissionLevel";

export interface ParticipantInviteRequest {
  /** @nullable */
  email?: string | null;
  permissionLevel?: ArticlePermissionLevel;
}
