/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { ArticlePermissionLevel } from "./articlePermissionLevel";

export interface SetParticipantRequest {
  accountId?: string;
  permissionLevel?: ArticlePermissionLevel;
}
