/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */

export interface TextDiff {
  /** @nullable */
  content?: string | null;
  isOriginal?: boolean;
  start?: number;
  end?: number;
}
