/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import type { Account } from "./account";

export interface User {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  readonly email?: string | null;
  account?: Account;
}
