/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { computed, unref } from "vue";
import type { MaybeRef } from "vue";
import type { ArticleDto } from "../model";
import { createInstance } from "../api-instance";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const getAccountAccountNameArticleTitle = (
  accountName: MaybeRef<string>,
  title: MaybeRef<string>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  accountName = unref(accountName);
  title = unref(title);

  return createInstance<ArticleDto>(
    { url: `/account/${accountName}/article/${title}`, method: "GET", signal },
    options,
  );
};

export const getGetAccountAccountNameArticleTitleQueryKey = (
  accountName: MaybeRef<string>,
  title: MaybeRef<string>,
) => {
  return ["account", accountName, "article", title] as const;
};

export const getGetAccountAccountNameArticleTitleQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccountAccountNameArticleTitle>>,
  TError = unknown,
>(
  accountName: MaybeRef<string>,
  title: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccountAccountNameArticleTitle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAccountAccountNameArticleTitleQueryKey(
    accountName,
    title,
  );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccountAccountNameArticleTitle>>
  > = ({ signal }) =>
    getAccountAccountNameArticleTitle(
      accountName,
      title,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(accountName) && unref(title))),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccountAccountNameArticleTitle>>,
    TError,
    TData
  >;
};

export type GetAccountAccountNameArticleTitleQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountAccountNameArticleTitle>>
>;
export type GetAccountAccountNameArticleTitleQueryError = unknown;

export function useGetAccountAccountNameArticleTitle<
  TData = Awaited<ReturnType<typeof getAccountAccountNameArticleTitle>>,
  TError = unknown,
>(
  accountName: MaybeRef<string>,
  title: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccountAccountNameArticleTitle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAccountAccountNameArticleTitleQueryOptions(
    accountName,
    title,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
