/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { computed, unref } from "vue";
import type { MaybeRef } from "vue";
import type { AccountArticleGetParams, Article } from "../model";
import { createInstance } from "../api-instance";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const accountArticleGet = (
  accountName: MaybeRef<string>,
  articleName: MaybeRef<string>,
  params?: MaybeRef<AccountArticleGetParams>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  accountName = unref(accountName);
  articleName = unref(articleName);
  params = unref(params);

  return createInstance<Article>(
    {
      url: `/account/${accountName}/article/${articleName}`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getAccountArticleGetQueryKey = (
  accountName: MaybeRef<string>,
  articleName: MaybeRef<string>,
  params?: MaybeRef<AccountArticleGetParams>,
) => {
  return [
    "account",
    accountName,
    "article",
    articleName,
    ...(params ? [params] : []),
  ] as const;
};

export const getAccountArticleGetQueryOptions = <
  TData = Awaited<ReturnType<typeof accountArticleGet>>,
  TError = unknown,
>(
  accountName: MaybeRef<string>,
  articleName: MaybeRef<string>,
  params?: MaybeRef<AccountArticleGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountArticleGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getAccountArticleGetQueryKey(
    accountName,
    articleName,
    params,
  );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountArticleGet>>
  > = ({ signal }) =>
    accountArticleGet(accountName, articleName, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!(unref(accountName) && unref(articleName))),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof accountArticleGet>>,
    TError,
    TData
  >;
};

export type AccountArticleGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountArticleGet>>
>;
export type AccountArticleGetQueryError = unknown;

export function useAccountArticleGet<
  TData = Awaited<ReturnType<typeof accountArticleGet>>,
  TError = unknown,
>(
  accountName: MaybeRef<string>,
  articleName: MaybeRef<string>,
  params?: MaybeRef<AccountArticleGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountArticleGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAccountArticleGetQueryOptions(
    accountName,
    articleName,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
