/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { computed, unref } from "vue";
import type { MaybeRef } from "vue";
import type { GetAccountAccountNameParams, ProfileDto } from "../model";
import { createInstance } from "../api-instance";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const getAccountSession = (
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<ProfileDto>(
    { url: `/account/session`, method: "GET", signal },
    options,
  );
};

export const getGetAccountSessionQueryKey = () => {
  return ["account", "session"] as const;
};

export const getGetAccountSessionQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccountSession>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAccountSession>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAccountSessionQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccountSession>>
  > = ({ signal }) => getAccountSession(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccountSession>>,
    TError,
    TData
  >;
};

export type GetAccountSessionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountSession>>
>;
export type GetAccountSessionQueryError = unknown;

export function useGetAccountSession<
  TData = Awaited<ReturnType<typeof getAccountSession>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAccountSession>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAccountSessionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export const getAccountAccountName = (
  accountName: MaybeRef<string>,
  params?: MaybeRef<GetAccountAccountNameParams>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  accountName = unref(accountName);
  params = unref(params);

  return createInstance<ProfileDto>(
    {
      url: `/account/${accountName}`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetAccountAccountNameQueryKey = (
  accountName: MaybeRef<string>,
  params?: MaybeRef<GetAccountAccountNameParams>,
) => {
  return ["account", accountName, ...(params ? [params] : [])] as const;
};

export const getGetAccountAccountNameQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccountAccountName>>,
  TError = unknown,
>(
  accountName: MaybeRef<string>,
  params?: MaybeRef<GetAccountAccountNameParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccountAccountName>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAccountAccountNameQueryKey(accountName, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccountAccountName>>
  > = ({ signal }) =>
    getAccountAccountName(accountName, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(accountName)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccountAccountName>>,
    TError,
    TData
  >;
};

export type GetAccountAccountNameQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountAccountName>>
>;
export type GetAccountAccountNameQueryError = unknown;

export function useGetAccountAccountName<
  TData = Awaited<ReturnType<typeof getAccountAccountName>>,
  TError = unknown,
>(
  accountName: MaybeRef<string>,
  params?: MaybeRef<GetAccountAccountNameParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAccountAccountName>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAccountAccountNameQueryOptions(
    accountName,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
