/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { computed, unref } from "vue";
import type { MaybeRef } from "vue";
import type { ArticleParticipant, ParticipantInviteRequest } from "../model";
import { createInstance } from "../api-instance";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const participantGetAllByArticle = (
  articleId: MaybeRef<string>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  articleId = unref(articleId);

  return createInstance<ArticleParticipant[]>(
    { url: `/participant/${articleId}`, method: "GET", signal },
    options,
  );
};

export const getParticipantGetAllByArticleQueryKey = (
  articleId: MaybeRef<string>,
) => {
  return ["participant", articleId] as const;
};

export const getParticipantGetAllByArticleQueryOptions = <
  TData = Awaited<ReturnType<typeof participantGetAllByArticle>>,
  TError = unknown,
>(
  articleId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof participantGetAllByArticle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getParticipantGetAllByArticleQueryKey(articleId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof participantGetAllByArticle>>
  > = ({ signal }) =>
    participantGetAllByArticle(articleId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(articleId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof participantGetAllByArticle>>,
    TError,
    TData
  >;
};

export type ParticipantGetAllByArticleQueryResult = NonNullable<
  Awaited<ReturnType<typeof participantGetAllByArticle>>
>;
export type ParticipantGetAllByArticleQueryError = unknown;

export function useParticipantGetAllByArticle<
  TData = Awaited<ReturnType<typeof participantGetAllByArticle>>,
  TError = unknown,
>(
  articleId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof participantGetAllByArticle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getParticipantGetAllByArticleQueryOptions(
    articleId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export const participantInvite = (
  articleId: MaybeRef<string>,
  participantInviteRequest: MaybeRef<ParticipantInviteRequest>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  articleId = unref(articleId);
  participantInviteRequest = unref(participantInviteRequest);

  return createInstance<void>(
    {
      url: `/participant/${articleId}/invite`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: participantInviteRequest,
      signal,
    },
    options,
  );
};

export const getParticipantInviteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof participantInvite>>,
    TError,
    { articleId: string; data: ParticipantInviteRequest },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof participantInvite>>,
  TError,
  { articleId: string; data: ParticipantInviteRequest },
  TContext
> => {
  const mutationKey = ["participantInvite"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof participantInvite>>,
    { articleId: string; data: ParticipantInviteRequest }
  > = (props) => {
    const { articleId, data } = props ?? {};

    return participantInvite(articleId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ParticipantInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof participantInvite>>
>;
export type ParticipantInviteMutationBody = ParticipantInviteRequest;
export type ParticipantInviteMutationError = unknown;

export const useParticipantInvite = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof participantInvite>>,
    TError,
    { articleId: string; data: ParticipantInviteRequest },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof participantInvite>>,
  TError,
  { articleId: string; data: ParticipantInviteRequest },
  TContext
> => {
  const mutationOptions = getParticipantInviteMutationOptions(options);

  return useMutation(mutationOptions);
};
