/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EScience.Application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { computed, unref } from "vue";
import type { MaybeRef } from "vue";
import type {
  Article,
  ArticleParticipant,
  CreateArticleRequest,
  SetParticipantRequest,
} from "../model";
import { createInstance } from "../api-instance";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const articleCreate = (
  createArticleRequest: MaybeRef<CreateArticleRequest>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  createArticleRequest = unref(createArticleRequest);

  return createInstance<Article>(
    {
      url: `/articles/create`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createArticleRequest,
      signal,
    },
    options,
  );
};

export const getArticleCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof articleCreate>>,
    TError,
    { data: CreateArticleRequest },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof articleCreate>>,
  TError,
  { data: CreateArticleRequest },
  TContext
> => {
  const mutationKey = ["articleCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof articleCreate>>,
    { data: CreateArticleRequest }
  > = (props) => {
    const { data } = props ?? {};

    return articleCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ArticleCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof articleCreate>>
>;
export type ArticleCreateMutationBody = CreateArticleRequest;
export type ArticleCreateMutationError = unknown;

export const useArticleCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof articleCreate>>,
    TError,
    { data: CreateArticleRequest },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof articleCreate>>,
  TError,
  { data: CreateArticleRequest },
  TContext
> => {
  const mutationOptions = getArticleCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const articleGetAll = (
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<Article[]>(
    { url: `/articles`, method: "GET", signal },
    options,
  );
};

export const getArticleGetAllQueryKey = () => {
  return ["articles"] as const;
};

export const getArticleGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof articleGetAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof articleGetAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getArticleGetAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof articleGetAll>>> = ({
    signal,
  }) => articleGetAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof articleGetAll>>,
    TError,
    TData
  >;
};

export type ArticleGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof articleGetAll>>
>;
export type ArticleGetAllQueryError = unknown;

export function useArticleGetAll<
  TData = Awaited<ReturnType<typeof articleGetAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof articleGetAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getArticleGetAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export const articleGet = (
  articleId: MaybeRef<string>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  articleId = unref(articleId);

  return createInstance<Article>(
    { url: `/articles/${articleId}`, method: "GET", signal },
    options,
  );
};

export const getArticleGetQueryKey = (articleId: MaybeRef<string>) => {
  return ["articles", articleId] as const;
};

export const getArticleGetQueryOptions = <
  TData = Awaited<ReturnType<typeof articleGet>>,
  TError = unknown,
>(
  articleId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articleGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getArticleGetQueryKey(articleId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof articleGet>>> = ({
    signal,
  }) => articleGet(articleId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(articleId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof articleGet>>, TError, TData>;
};

export type ArticleGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof articleGet>>
>;
export type ArticleGetQueryError = unknown;

export function useArticleGet<
  TData = Awaited<ReturnType<typeof articleGet>>,
  TError = unknown,
>(
  articleId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof articleGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof createInstance>;
  },
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getArticleGetQueryOptions(articleId, options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export const articleSetParticipant = (
  articleId: MaybeRef<string>,
  setParticipantRequest: MaybeRef<SetParticipantRequest>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  articleId = unref(articleId);
  setParticipantRequest = unref(setParticipantRequest);

  return createInstance<ArticleParticipant>(
    {
      url: `/articles/set_participant_for_article/${articleId}`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: setParticipantRequest,
      signal,
    },
    options,
  );
};

export const getArticleSetParticipantMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof articleSetParticipant>>,
    TError,
    { articleId: string; data: SetParticipantRequest },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof articleSetParticipant>>,
  TError,
  { articleId: string; data: SetParticipantRequest },
  TContext
> => {
  const mutationKey = ["articleSetParticipant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof articleSetParticipant>>,
    { articleId: string; data: SetParticipantRequest }
  > = (props) => {
    const { articleId, data } = props ?? {};

    return articleSetParticipant(articleId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ArticleSetParticipantMutationResult = NonNullable<
  Awaited<ReturnType<typeof articleSetParticipant>>
>;
export type ArticleSetParticipantMutationBody = SetParticipantRequest;
export type ArticleSetParticipantMutationError = unknown;

export const useArticleSetParticipant = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof articleSetParticipant>>,
    TError,
    { articleId: string; data: SetParticipantRequest },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof articleSetParticipant>>,
  TError,
  { articleId: string; data: SetParticipantRequest },
  TContext
> => {
  const mutationOptions = getArticleSetParticipantMutationOptions(options);

  return useMutation(mutationOptions);
};
